id: P9C4C1444
initial_creation_type: ocr
source_metadata:
  volumes:
    a95767dfa5f84caeb28d38075e21cb66:
      base_file: v071.txt
      image_group_id: I1PD95916
      title: ཆོས་དང་ཆོས་ཉིད་རྣམ་པར་འབྱེད་པའི་འགྲེལ་པ།
      total_pages: 1683
      volume_number: 71
